# Generated by Django 3.1.3 on 2020-12-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number_of_seasons', models.IntegerField(default=0)),
                ('release_year', models.DateField(auto_now=True, max_length=4)),
                ('api_title', models.CharField(default=0, max_length=200)),
                ('slug', models.CharField(default=0, max_length=200)),
                ('imdb', models.CharField(default=0, max_length=100)),
            ],
            options={
                'unique_together': {('title', 'release_year')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.TextField(max_length=1000)),
                ('rate', models.IntegerField(default=1)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors_list.serial')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('serials', models.ManyToManyField(to='actors_list.Serial')),
            ],
        ),
    ]
