# Generated by Django 3.1.3 on 2020-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0002_serial_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='number_of_seasons',
            field=models.IntegerField(default=0),
        ),
    ]
