# Generated by Django 3.1.3 on 2020-12-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0002_auto_20201208_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='release_year',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
