# Generated by Django 3.1.3 on 2020-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0003_auto_20201208_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
