# Generated by Django 3.1.3 on 2020-11-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0003_serial_number_of_seasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='completed',
            new_name='finished',
        ),
    ]
