# Generated by Django 3.1.3 on 2020-11-27 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0004_auto_20201126_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='finished',
        ),
        migrations.AddField(
            model_name='serial',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
