# Generated by Django 3.1.3 on 2020-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0005_auto_20201127_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('actors', models.ManyToManyField(to='actors_list.Serial')),
            ],
        ),
    ]
