# Generated by Django 3.1.3 on 2020-12-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0005_auto_20201208_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='release_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
