# Generated by Django 3.1.3 on 2020-11-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0006_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actors',
            new_name='serials',
        ),
    ]
