# Generated by Django 3.1.3 on 2020-12-09 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0006_auto_20201209_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='release_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1800)]),
        ),
    ]
