# Generated by Django 3.1.3 on 2020-11-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0007_auto_20201128_1344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serial',
            unique_together={('title', 'release_date')},
        ),
    ]
