# Generated by Django 3.1.3 on 2020-11-28 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0008_auto_20201128_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.TextField(max_length=1000)),
                ('raiting', models.IntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
    ]
