# Generated by Django 3.1.3 on 2020-11-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0011_auto_20201129_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='serial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actors_list.serial'),
        ),
    ]
