# Generated by Django 3.1.3 on 2020-11-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0012_comment_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='serial',
            field=models.ForeignKey(default=55932336, on_delete=django.db.models.deletion.CASCADE, to='actors_list.serial'),
        ),
    ]
