# Generated by Django 3.1.3 on 2020-11-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0014_auto_20201129_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors_list.serial'),
        ),
    ]
