# Generated by Django 3.1.3 on 2020-12-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_list', '0015_auto_20201130_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='api_title',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='serial',
            name='imdb',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='serial',
            name='slug',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='serial',
            name='release_date',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
